[tox]
envlist =
  py39
  py310
  py311

[testenv]
deps =
  pipenv>=2025.0.3

allowlist_externals =
  pipenv

commands =
  pipenv sync -d
  pipenv run ruff check monkeytype
  pipenv run ruff format --check --diff monkeytype
  pipenv run isort --check --diff monkeytype
  pipenv run mypy monkeytype
  pipenv run pytest
