[tox]
envlist =
  py38
  py39
  py310
  py311

[testenv]
deps =
  pipenv>=2025.0.3

commands =
  pipenv sync -d
  pipenv run flake8
  pipenv run black --check --diff monkeytype
  pipenv run isort --check --diff monkeytype
  pipenv run mypy monkeytype
  pipenv run pytest
